---
# tasks file for postgresql
- name: include distribution dependency variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution_file_variety }}.yml"

- name: Install and configure PostgreSql Tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety }}-{{ ansible_distribution_major_version }}-install.yml"
    - "{{ ansible_distribution_file_variety }}-install.yml"

- name: Configure postgresql tasks
  include_tasks: "{{ item }}"
  with_items:
    - "{{ ansible_distribution_file_variety }}-configure.yml"

- include_tasks: init_databases.yml